import { concludeDeployment, materializeDeployment, totalDurationMs } from "./engine"
import type {
  ActivityEvent,
  AppState,
  Container,
  Deployment,
  Domain,
  EnvironmentVariable,
  GitRepository,
  LogEntry,
  Project,
  ProjectSource,
  Volume,
} from "./types"
import { SCHEMA_VERSION } from "./types"
import { dnsRecordsFor } from "./helpers"

const minute = 60_000
const hour = 60 * minute
const day = 24 * hour

function env(partial: EnvironmentVariable): EnvironmentVariable {
  return partial
}

function github(owner: string, repo: string): ProjectSource {
  return { type: "github", owner, repo, fullName: `${owner}/${repo}` }
}

export function createInitialState(now: number): AppState {
  const ago = (ms: number) => new Date(now - ms).toISOString()
  const duration = totalDurationMs()

  const arciinEnv: EnvironmentVariable[] = [
    env({
      id: "env_arciin_db",
      key: "DATABASE_URL",
      value: "postgres://arciin:arc-lab-demo-password@arciin-db:5432/arciin",
      secret: true,
      scope: "production",
    }),
    env({
      id: "env_arciin_url",
      key: "NEXT_PUBLIC_APP_URL",
      value: "http://arciin.local",
      secret: false,
      scope: "all",
    }),
    env({
      id: "env_arciin_license",
      key: "ARC_LICENSE",
      value: "arc_lab_demo_license",
      secret: true,
      scope: "production",
    }),
  ]

  const modvraEnv: EnvironmentVariable[] = [
    env({
      id: "env_modvra_db",
      key: "DATABASE_URL",
      value: "mysql://modvra:arc-lab-demo-password@modvra-db:3306/modvra",
      secret: true,
      scope: "production",
    }),
    env({
      id: "env_modvra_bucket",
      key: "MEDIA_BUCKET",
      value: "modvra-media",
      secret: false,
      scope: "production",
    }),
  ]

  const apiEnv: EnvironmentVariable[] = [
    env({
      id: "env_api_env",
      key: "APP_ENV",
      value: "development",
      secret: false,
      scope: "development",
    }),
  ]

  const projects: Project[] = [
    {
      id: "proj_arciin",
      name: "Arciin",
      slug: "arciin",
      environment: "production",
      framework: "nextjs",
      source: github("Roberadesissaii", "arciin"),
      branch: "main",
      commitSha: "8f34a91",
      commitMessage: "Deploy dashboard redesign",
      packageManager: "pnpm",
      installCommand: "pnpm install",
      buildCommand: "pnpm build",
      startCommand: "pnpm start",
      outputDirectory: ".next",
      rootDirectory: ".",
      internalPort: 3000,
      exposedPort: 8082,
      portMode: "auto",
      healthPath: "/",
      restartPolicy: "unless-stopped",
      cpuLimit: null,
      memoryLimitMb: null,
      autoDeploy: true,
      hostname: "arciin.local",
      createdAt: ago(42 * day),
      updatedAt: ago(18 * minute),
      runtime: "running",
      simulateFailure: false,
      env: arciinEnv,
      liveDeploymentId: "dep_arciin_current",
    },
    {
      id: "proj_modvra",
      name: "MODVRA Studio",
      slug: "modvra-studio",
      environment: "production",
      framework: "nextjs",
      source: github("Roberadesissaii", "modvra-studio"),
      branch: "main",
      commitSha: "c21ab70",
      commitMessage: "Publish studio homepage",
      packageManager: "pnpm",
      installCommand: "pnpm install",
      buildCommand: "pnpm build",
      startCommand: "pnpm start",
      outputDirectory: ".next",
      rootDirectory: ".",
      internalPort: 3000,
      exposedPort: 8083,
      portMode: "auto",
      healthPath: "/",
      restartPolicy: "unless-stopped",
      cpuLimit: null,
      memoryLimitMb: null,
      autoDeploy: true,
      hostname: "modvra.local",
      createdAt: ago(30 * day),
      updatedAt: ago(2 * hour),
      runtime: "running",
      simulateFailure: false,
      env: modvraEnv,
      liveDeploymentId: "dep_modvra_current",
    },
    {
      id: "proj_api",
      name: "API Sandbox",
      slug: "api-sandbox",
      environment: "development",
      framework: "fastapi",
      source: { type: "upload", filename: "api-sandbox.zip", size: 1_843_200 },
      branch: null,
      commitSha: "91de440",
      commitMessage: "Add sandbox health route",
      packageManager: "pip",
      installCommand: "pip install -r requirements.txt",
      buildCommand: "python -m compileall app",
      startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000",
      outputDirectory: null,
      rootDirectory: ".",
      internalPort: 8000,
      exposedPort: 8084,
      portMode: "auto",
      healthPath: "/health",
      restartPolicy: "on-failure",
      cpuLimit: 1,
      memoryLimitMb: 512,
      autoDeploy: false,
      hostname: "api-sandbox.local",
      createdAt: ago(6 * day),
      updatedAt: ago(4 * day),
      runtime: "running",
      simulateFailure: false,
      env: apiEnv,
      liveDeploymentId: "dep_api_ready",
    },
  ]

  function makeDeployment(input: {
    id: string
    project: Project
    sha: string
    message: string
    startedAgo: number
    failAt?: Deployment["failAt"]
    previousRelease: boolean
    branch?: string | null
  }): Deployment {
    const startedAt = ago(input.startedAgo)
    const draft: Deployment = {
      id: input.id,
      projectId: input.project.id,
      environment: input.project.environment,
      status: "queued",
      phase: "queued",
      steps: [],
      branch: input.branch === undefined ? input.project.branch : input.branch,
      commitSha: input.sha,
      commitMessage: input.message,
      createdAt: startedAt,
      startedAt,
      finishedAt: null,
      triggeredBy: "Robera",
      failAt: input.failAt ?? null,
      previousRelease: input.previousRelease,
      error: null,
      sourceLabel:
        input.project.source.type === "github"
          ? `${input.project.source.fullName} · ${input.branch ?? input.project.branch ?? "main"}`
          : input.project.source.type === "upload"
            ? input.project.source.filename
            : input.project.name,
    }
    return concludeDeployment(draft)
  }

  const deployments: Deployment[] = [
    makeDeployment({
      id: "dep_arciin_prev",
      project: projects[0],
      sha: "11ab902",
      message: "Tighten file browser spacing",
      startedAgo: 2 * day,
      previousRelease: false,
    }),
    makeDeployment({
      id: "dep_arciin_current",
      project: projects[0],
      sha: "8f34a91",
      message: "Deploy dashboard redesign",
      startedAgo: 18 * minute + duration,
      previousRelease: true,
    }),
    makeDeployment({
      id: "dep_modvra_current",
      project: projects[1],
      sha: "c21ab70",
      message: "Publish studio homepage",
      startedAgo: 2 * hour + duration,
      previousRelease: false,
    }),
    makeDeployment({
      id: "dep_api_failed",
      project: projects[2],
      sha: "b10aa02",
      message: "First sandbox import",
      startedAgo: 5 * day,
      failAt: "building",
      previousRelease: false,
    }),
    makeDeployment({
      id: "dep_api_ready",
      project: projects[2],
      sha: "91de440",
      message: "Add sandbox health route",
      startedAgo: 4 * day + duration,
      previousRelease: false,
    }),
    materializeDeployment(
      {
        id: "dep_api_current",
        projectId: "proj_api",
        environment: "development",
        status: "queued",
        phase: "queued",
        steps: [],
        branch: null,
        commitSha: "e4c91aa",
        commitMessage: "Exercise upload pipeline",
        createdAt: ago(4200),
        startedAt: ago(4200),
        finishedAt: null,
        triggeredBy: "Robera",
        failAt: null,
        previousRelease: true,
        error: null,
        sourceLabel: "api-sandbox.zip",
      },
      now,
    ),
  ]

  const containers: Container[] = [
    {
      id: "ctr_arciin_web",
      name: "arciin-web",
      serverId: "srv_home",
      projectId: "proj_arciin",
      role: "web",
      image: "arcellite/arciin:8f34a91",
      state: "running",
      startedAt: ago(18 * minute),
      stateChangedAt: ago(18 * minute),
      cpuPercent: 2.4,
      memoryMb: 382,
      ports: [{ host: 8082, container: 3000, protocol: "tcp" }],
      command: "pnpm start",
      restartPolicy: "unless-stopped",
    },
    {
      id: "ctr_arciin_worker",
      name: "arciin-worker",
      serverId: "srv_home",
      projectId: "proj_arciin",
      role: "worker",
      image: "arcellite/arciin-worker:8f34a91",
      state: "running",
      startedAt: ago(hour),
      stateChangedAt: ago(hour),
      cpuPercent: 0.4,
      memoryMb: 96,
      ports: [],
      command: "node worker.js",
      restartPolicy: "on-failure",
    },
    {
      id: "ctr_modvra_web",
      name: "modvra-web",
      serverId: "srv_home",
      projectId: "proj_modvra",
      role: "web",
      image: "arcellite/modvra-studio:c21ab70",
      state: "running",
      startedAt: ago(2 * hour),
      stateChangedAt: ago(2 * hour),
      cpuPercent: 1.1,
      memoryMb: 410,
      ports: [{ host: 8083, container: 3000, protocol: "tcp" }],
      command: "pnpm start",
      restartPolicy: "unless-stopped",
    },
    {
      id: "ctr_api",
      name: "api-sandbox",
      serverId: "srv_home",
      projectId: "proj_api",
      role: "web",
      image: "arcellite/api-sandbox:91de440",
      state: "running",
      startedAt: ago(4 * day),
      stateChangedAt: ago(4 * day),
      cpuPercent: 3.2,
      memoryMb: 220,
      ports: [{ host: 8084, container: 8000, protocol: "tcp" }],
      command: "uvicorn app.main:app --host 0.0.0.0 --port 8000",
      restartPolicy: "on-failure",
    },
    {
      id: "ctr_mysql",
      name: "modvra-db",
      serverId: "srv_home",
      projectId: "proj_modvra",
      role: "data",
      image: "mysql:8.4",
      state: "running",
      startedAt: ago(12 * day),
      stateChangedAt: ago(12 * day),
      cpuPercent: 0.6,
      memoryMb: 480,
      ports: [{ host: null, container: 3306, protocol: "tcp" }],
      command: "mysqld",
      restartPolicy: "unless-stopped",
    },
    {
      id: "ctr_postgres",
      name: "postgres",
      serverId: "srv_home",
      projectId: "proj_arciin",
      role: "data",
      image: "postgres:17",
      state: "running",
      startedAt: ago(18 * day),
      stateChangedAt: ago(18 * day),
      cpuPercent: 0.8,
      memoryMb: 512,
      ports: [{ host: null, container: 5432, protocol: "tcp" }],
      command: "postgres",
      restartPolicy: "unless-stopped",
    },
    {
      id: "ctr_redis",
      name: "redis",
      serverId: "srv_home",
      projectId: null,
      role: "data",
      image: "redis:7.4",
      state: "running",
      startedAt: ago(18 * day),
      stateChangedAt: ago(18 * day),
      cpuPercent: 0.2,
      memoryMb: 48,
      ports: [{ host: null, container: 6379, protocol: "tcp" }],
      command: "redis-server",
      restartPolicy: "unless-stopped",
    },
  ]

  const volumes: Volume[] = [
    {
      id: "vol_pg",
      name: "postgres-data",
      serverId: "srv_home",
      sizeGb: 12.8,
      path: "/var/lib/docker/volumes/postgres-data/_data",
      attachedTo: "postgres",
      attachmentLabel: "Attached to postgres",
      lastBackupAt: ago(14 * hour),
      createdAt: ago(40 * day),
    },
    {
      id: "vol_uploads",
      name: "uploads",
      serverId: "srv_home",
      sizeGb: 4.2,
      path: "/var/lib/docker/volumes/uploads/_data",
      attachedTo: "arciin-web",
      attachmentLabel: "Attached to arciin-web",
      lastBackupAt: ago(26 * hour),
      createdAt: ago(36 * day),
    },
    {
      id: "vol_modvra",
      name: "modvra-media",
      serverId: "srv_home",
      sizeGb: 8.1,
      path: "/var/lib/docker/volumes/modvra-media/_data",
      attachedTo: "modvra-web",
      attachmentLabel: "Attached to modvra-web",
      lastBackupAt: ago(3 * day),
      createdAt: ago(28 * day),
    },
    {
      id: "vol_redis",
      name: "redis-data",
      serverId: "srv_home",
      sizeGb: 0.4,
      path: "/var/lib/docker/volumes/redis-data/_data",
      attachedTo: "redis",
      attachmentLabel: "Attached to redis",
      lastBackupAt: ago(20 * hour),
      createdAt: ago(40 * day),
    },
  ]

  const domains: Domain[] = [
    {
      id: "dom_arciin",
      name: "arciin.local",
      kind: "private",
      projectId: "proj_arciin",
      targetPort: 8082,
      status: "active",
      ssl: "none",
      createdAt: ago(20 * day),
      verifiedAt: ago(20 * day),
      verifyStartedAt: null,
      failVerification: false,
      records: [],
      error: null,
    },
    {
      id: "dom_modvra",
      name: "modvra.local",
      kind: "private",
      projectId: "proj_modvra",
      targetPort: 8083,
      status: "active",
      ssl: "none",
      createdAt: ago(12 * day),
      verifiedAt: ago(12 * day),
      verifyStartedAt: null,
      failVerification: false,
      records: [],
      error: null,
    },
    {
      id: "dom_api",
      name: "api.sandbox.dev",
      kind: "public",
      projectId: "proj_api",
      targetPort: 8084,
      status: "dns-required",
      ssl: "pending",
      createdAt: ago(3 * hour),
      verifiedAt: null,
      verifyStartedAt: null,
      failVerification: false,
      records: dnsRecordsFor("api.sandbox.dev"),
      error: null,
    },
  ]

  const activity: ActivityEvent[] = [
    {
      id: "act_api_build",
      action: "Deployment started",
      result: "info",
      objectType: "Deployment",
      objectName: "API Sandbox",
      href: "/deployments/dep_api_current",
      actor: "Robera",
      timestamp: ago(4200),
      detail: "Upload api-sandbox.zip",
    },
    {
      id: "act_arciin_ready",
      action: "Deployment succeeded",
      result: "success",
      objectType: "Deployment",
      objectName: "Arciin",
      href: "/deployments/dep_arciin_current",
      actor: "Robera",
      timestamp: ago(18 * minute),
      detail: "8f34a91 · Deploy dashboard redesign",
    },
    {
      id: "act_worker",
      action: "Container restarted",
      result: "warning",
      objectType: "Container",
      objectName: "arciin-worker",
      href: "/containers?inspect=ctr_arciin_worker",
      actor: "Robera",
      timestamp: ago(hour),
      detail: "Restart policy brought the worker back.",
    },
    {
      id: "act_modvra",
      action: "Deployment succeeded",
      result: "success",
      objectType: "Deployment",
      objectName: "MODVRA Studio",
      href: "/deployments/dep_modvra_current",
      actor: "Robera",
      timestamp: ago(2 * hour),
      detail: "c21ab70 · Publish studio homepage",
    },
    {
      id: "act_domain",
      action: "Domain configured",
      result: "info",
      objectType: "Domain",
      objectName: "api.sandbox.dev",
      href: "/domains",
      actor: "Robera",
      timestamp: ago(3 * hour),
      detail: "Waiting for DNS verification.",
    },
    {
      id: "act_env",
      action: "Environment variable updated",
      result: "info",
      objectType: "Project",
      objectName: "Arciin",
      href: "/projects/proj_arciin/environment",
      actor: "Robera",
      timestamp: ago(day),
      detail: "ARC_LICENSE rotated.",
    },
    {
      id: "act_server",
      action: "Server connected",
      result: "success",
      objectType: "Server",
      objectName: "home-server",
      href: "/servers/srv_home",
      actor: "Robera",
      timestamp: ago(18 * day),
      detail: "Ubuntu 24.04 LTS · 192.168.1.50",
    },
  ]

  const operationalLogs: LogEntry[] = [
    {
      id: "log_docker",
      targetType: "server",
      targetId: "srv_home",
      projectId: null,
      level: "info",
      message: "Docker Engine 27.3.1 is healthy",
      timestamp: ago(6 * hour),
    },
    {
      id: "log_heartbeat",
      targetType: "server",
      targetId: "srv_home",
      projectId: null,
      level: "debug",
      message: "Agent heartbeat accepted",
      timestamp: ago(2 * minute),
    },
    {
      id: "log_worker",
      targetType: "container",
      targetId: "ctr_arciin_worker",
      projectId: "proj_arciin",
      level: "warn",
      message: "Worker process exited. Restart policy brought it back.",
      timestamp: ago(hour),
    },
    {
      id: "log_pg",
      targetType: "container",
      targetId: "ctr_postgres",
      projectId: "proj_arciin",
      level: "debug",
      message: "checkpoint complete password=arc-lab-demo-password",
      timestamp: ago(30 * minute),
    },
    {
      id: "log_redis",
      targetType: "container",
      targetId: "ctr_redis",
      projectId: null,
      level: "info",
      message: "Ready to accept connections",
      timestamp: ago(18 * day),
    },
    {
      id: "log_api",
      targetType: "container",
      targetId: "ctr_api",
      projectId: "proj_api",
      level: "info",
      message: "Uvicorn running on port 8000",
      timestamp: ago(4 * day),
    },
  ]

  const repositories: GitRepository[] = [
    {
      id: "repo_arciin",
      owner: "Roberadesissaii",
      name: "arciin",
      fullName: "Roberadesissaii/arciin",
      private: true,
      language: "TypeScript",
      framework: "nextjs",
      description: "Product workspace for the Arciin dashboard.",
      defaultBranch: "main",
      branches: ["main", "feature/home"],
      updatedAt: ago(18 * minute),
      files: ["package.json", "pnpm-lock.yaml", "next.config.ts", "app/page.tsx", "app/layout.tsx"],
      importedProjectId: "proj_arciin",
    },
    {
      id: "repo_modvra",
      owner: "Roberadesissaii",
      name: "modvra-studio",
      fullName: "Roberadesissaii/modvra-studio",
      private: true,
      language: "TypeScript",
      framework: "nextjs",
      description: "Studio site and project archive.",
      defaultBranch: "main",
      branches: ["main"],
      updatedAt: ago(2 * hour),
      files: ["package.json", "pnpm-lock.yaml", "next.config.ts", "app/page.tsx"],
      importedProjectId: "proj_modvra",
    },
    {
      id: "repo_portfolio",
      owner: "Roberadesissaii",
      name: "portfolio",
      fullName: "Roberadesissaii/portfolio",
      private: false,
      language: "TypeScript",
      framework: "nextjs",
      description: "Personal site, ready to deploy.",
      defaultBranch: "main",
      branches: ["main", "feature/home"],
      updatedAt: ago(5 * hour),
      files: ["package.json", "pnpm-lock.yaml", "next.config.ts", "app/page.tsx"],
      importedProjectId: null,
    },
    {
      id: "repo_notes",
      owner: "Roberadesissaii",
      name: "notes-api",
      fullName: "Roberadesissaii/notes-api",
      private: true,
      language: "Python",
      framework: "fastapi",
      description: "Small notes API used for experiments.",
      defaultBranch: "main",
      branches: ["main", "dev"],
      updatedAt: ago(day),
      files: ["requirements.txt", "pyproject.toml", "app/main.py"],
      importedProjectId: null,
    },
    {
      id: "repo_status",
      owner: "Roberadesissaii",
      name: "status-page",
      fullName: "Roberadesissaii/status-page",
      private: false,
      language: "HTML",
      framework: "static",
      description: "Static status page for the lab.",
      defaultBranch: "main",
      branches: ["main"],
      updatedAt: ago(4 * day),
      files: ["index.html", "styles.css"],
      importedProjectId: null,
    },
    {
      id: "repo_worker",
      owner: "Roberadesissaii",
      name: "worker",
      fullName: "Roberadesissaii/worker",
      private: true,
      language: "TypeScript",
      framework: "express",
      description: "Background worker for file processing.",
      defaultBranch: "main",
      branches: ["main"],
      updatedAt: ago(8 * hour),
      files: ["package.json", "pnpm-lock.yaml", "src/server.ts"],
      importedProjectId: null,
    },
    {
      id: "repo_ui",
      owner: "Roberadesissaii",
      name: "component-lab",
      fullName: "Roberadesissaii/component-lab",
      private: false,
      language: "TypeScript",
      framework: "vite",
      description: "Vite sandbox for interface experiments.",
      defaultBranch: "main",
      branches: ["main"],
      updatedAt: ago(3 * day),
      files: ["package.json", "vite.config.ts", "index.html", "src/main.tsx"],
      importedProjectId: null,
    },
  ]

  return {
    schema: SCHEMA_VERSION,
    settings: {
      theme: "light",
      motion: "system",
      defaultBranch: "main",
      portAllocation: "auto",
      portStart: 8082,
      defaultEnvironment: "production",
      developerMode: false,
      redactSecrets: true,
      workspaceName: "Arcellite Lab",
      displayName: "Robera",
      timezone: "UTC",
      notifyDeploySuccess: true,
      notifyDeployFailure: true,
      notifyDomains: true,
      notifyServer: true,
      logRetentionDays: 14,
      buildConcurrency: 1,
      autoRollback: true,
    },
    onboardingComplete: false,
    github: {
      connected: true,
      accountName: "Robera",
      accountLogin: "Roberadesissaii",
    },
    servers: [
      {
        id: "srv_home",
        name: "home-server",
        status: "online",
        os: "Ubuntu 24.04 LTS",
        arch: "x86_64",
        ip: "192.168.1.50",
        iface: "eth0",
        cidr: "192.168.1.50/24",
        gateway: "192.168.1.1",
        dns: ["192.168.1.1"],
        cpuCount: 8,
        memoryTotalGb: 16,
        storageTotalGb: 512,
        memoryUsedGb: 4.8,
        storageUsedGb: 186,
        cpuPercent: 17,
        networkMbps: 14,
        dockerVersion: "27.3.1",
        dockerStatus: "running",
        agentVersion: "0.1.0-mock",
        agentStatus: "connected",
        startedAt: ago(18 * day + 4 * hour),
        sampleShift: 2,
        refreshedAt: null,
      },
    ],
    projects,
    deployments,
    containers,
    domains,
    volumes,
    databases: [
      {
        id: "db_arciin",
        name: "arciin-db",
        engine: "postgresql",
        version: "17",
        status: "running",
        serverId: "srv_home",
        projectId: "proj_arciin",
        containerId: "ctr_postgres",
        host: "arciin-db",
        port: 5432,
        username: "arciin",
        password: "arc-lab-demo-password",
        database: "arciin",
        storageGb: 18.4,
        volumeId: "vol_pg",
      },
      {
        id: "db_modvra",
        name: "modvra-db",
        engine: "mysql",
        version: "8.4",
        status: "running",
        serverId: "srv_home",
        projectId: "proj_modvra",
        containerId: "ctr_mysql",
        host: "modvra-db",
        port: 3306,
        username: "modvra",
        password: "arc-lab-demo-password",
        database: "modvra",
        storageGb: 6.2,
        volumeId: "vol_modvra",
      },
      {
        id: "db_redis",
        name: "cache",
        engine: "redis",
        version: "7.4",
        status: "running",
        serverId: "srv_home",
        projectId: null,
        containerId: "ctr_redis",
        host: "redis",
        port: 6379,
        username: null,
        password: null,
        database: null,
        storageGb: 0.4,
        volumeId: "vol_redis",
      },
    ],
    activity,
    operationalLogs,
    repositories,
  }
}
